"use client";

import { useState } from "react";
import { FileAudio, FileJson, FileText, Image as ImageIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SCAM_CATEGORY_LABELS, VoiceAnalysisResult } from "@/types/voiceAnalysis";
import {
  downloadBlob,
  downloadJsonFile,
  downloadTextFile,
  renderSummaryAsPng,
} from "@/lib/helpers/evidenceExport";
import { AudioPreviewData } from "./AudioPreview";
import { formatDuration, formatFileSize } from "./audioUtils";

interface EvidenceExportProps {
  audio: AudioPreviewData;
  result: VoiceAnalysisResult;
}

export function EvidenceExport({ audio, result }: EvidenceExportProps) {
  const [isExportingPng, setIsExportingPng] = useState(false);

  const buildSummaryText = () => {
    const lines: string[] = [];
    lines.push("VOICE SCAM ANALYSIS — LOCAL REPORT");
    lines.push(`Generated: ${new Date().toLocaleString()}`);
    lines.push("");
    lines.push(`Risk level: ${result.level}`);
    lines.push(`Confidence: ${result.confidence}`);
    lines.push(
      `Likely scam type: ${SCAM_CATEGORY_LABELS[result.scamType]}${
        result.scamTypeUncertain ? " (uncertain)" : ""
      }`
    );
    lines.push("");
    lines.push("Summary:");
    lines.push(result.summary);
    lines.push("");
    if (result.signals.length > 0) {
      lines.push("Detected signals:");
      result.signals.forEach((s) => {
        lines.push(`- ${s.label} (${s.confidence}%): ${s.explanation}`);
      });
      lines.push("");
    }
    if (result.protectionSteps.length > 0) {
      lines.push("Recommended protection steps:");
      result.protectionSteps.forEach((step, i) => lines.push(`${i + 1}. ${step}`));
      lines.push("");
    }
    lines.push(`Audio: ${audio.name} (${formatFileSize(audio.sizeBytes)}, ${formatDuration(audio.durationSeconds)})`);
    lines.push(`File type: ${result.metadata.fileType}`);
    lines.push("");
    lines.push("--");
    lines.push(
      "Transcript was generated by Google Gemini and the analysis is heuristic. This report is generated locally and is NOT submitted to any authority."
    );
    return lines.join("\n");
  };

  const handleExportPng = async () => {
    setIsExportingPng(true);
    try {
      const dataUrl = await renderSummaryAsPng(buildSummaryText());
      const blob = await (await fetch(dataUrl)).blob();
      downloadBlob(`voice-analysis-${Date.now()}.png`, blob);
    } finally {
      setIsExportingPng(false);
    }
  };

  return (
    <div className="space-y-2">
      <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
        Save your evidence (stays on your device)
      </p>
      <div className="flex flex-wrap gap-2">
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() =>
            downloadBlob(`voice-recording-${Date.now()}.webm`, audio.blob)
          }
        >
          <FileAudio className="h-4 w-4 mr-1.5" />
          Audio
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() =>
            downloadTextFile(
              `voice-transcript-${Date.now()}.txt`,
              `Transcript of ${audio.name}\n\n${result.transcript}`
            )
          }
        >
          <FileText className="h-4 w-4 mr-1.5" />
          Transcript
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() =>
            downloadJsonFile(
              `voice-analysis-${Date.now()}.json`,
              { ...result, audioFile: audio.name, generatedAt: new Date().toISOString() }
            )
          }
        >
          <FileJson className="h-4 w-4 mr-1.5" />
          Analysis (JSON)
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={handleExportPng}
          disabled={isExportingPng}
        >
          <ImageIcon className="h-4 w-4 mr-1.5" />
          {isExportingPng ? "Generating…" : "Summary Image"}
        </Button>
      </div>
    </div>
  );
}