"use client";

import {
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  AlertTriangle,
  Siren,
  Fingerprint,
  Bot,
  RotateCcw,
  LifeBuoy,
} from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { SCAM_CATEGORY_LABELS, VoiceAnalysisResult } from "@/types/voiceAnalysis";
import { cn } from "@/lib/utils";
import { TranscriptDisplay } from "./TranscriptDisplay";
import { VoiceFingerprint } from "./VoiceFingerprint";
import { EvidenceExport } from "./EvidenceExport";
import { AudioPreviewData } from "./AudioPreview";
import { formatDuration, formatFileSize } from "./audioUtils";

interface VoiceRiskResultProps {
  result: VoiceAnalysisResult;
  audio: AudioPreviewData;
  onReset?: () => void;
}

export function VoiceRiskResult({ result, audio, onReset }: VoiceRiskResultProps) {
  const isHighRisk = result.level === "HIGH_RISK";

  const levelMeta = isHighRisk
    ? {
        icon: ShieldX,
        title: "High Risk",
        description:
          "Strong scam indicators were detected in this audio. Do not follow the caller's instructions.",
        className: "border-destructive/30 bg-destructive/5 text-destructive",
        badge: "destructive" as const,
      }
    : result.level === "SUSPICIOUS"
      ? {
          icon: ShieldAlert,
          title: "Suspicious",
          description:
            "Several scam-like patterns were detected. Treat this call with strong caution.",
          className: "border-warning/40 bg-warning/10 text-warning-foreground",
          badge: "secondary" as const,
        }
      : {
          icon: ShieldCheck,
          title: "No obvious threat detected",
          description:
            "We did not find strong scam patterns in this audio. Stay alert — this does not guarantee safety.",
          className: "border-emerald-300 bg-emerald-50 text-emerald-700",
          badge: "secondary" as const,
        };

  const LevelIcon = levelMeta.icon;

  return (
    <div className="space-y-6">
      <div
        className={cn(
          "rounded-xl border p-5 space-y-3",
          levelMeta.className
        )}
      >
        <div className="flex items-start gap-3">
          <div className="h-11 w-11 rounded-full bg-background/80 flex items-center justify-center shrink-0">
            <LevelIcon className="h-6 w-6" />
          </div>
          <div className="space-y-1">
            <div className="flex items-center gap-2 flex-wrap">
              <h3 className="text-lg font-semibold">{levelMeta.title}</h3>
              <Badge variant={levelMeta.badge}>Confidence: {result.confidence}</Badge>
            </div>
            <p className="text-sm opacity-90">{levelMeta.description}</p>
          </div>
        </div>

        <div className="flex items-center gap-1.5 text-xs opacity-80">
          <Bot className="h-3.5 w-3.5" />
          Transcript generated by Google Gemini; signals detected by our pattern engine.
        </div>
      </div>

      {result.scamType !== "OTHER" && (
        <div className="rounded-xl border border-border bg-muted/30 p-4">
          <div className="flex items-center gap-2 flex-wrap">
            <Fingerprint className="h-4 w-4 text-primary" />
            <p className="text-sm font-medium">Likely scam type</p>
          </div>
          <p className="mt-1.5 text-base font-semibold">
            {SCAM_CATEGORY_LABELS[result.scamType]}
            {result.scamTypeUncertain && (
              <span className="text-xs font-normal text-muted-foreground ml-2">
                (pattern match is not strong enough to be certain)
              </span>
            )}
          </p>
        </div>
      )}

      <div className="rounded-xl border border-border p-4">
        <h4 className="text-sm font-medium mb-2 flex items-center gap-2">
          <AlertTriangle className="h-4 w-4 text-warning" />
          Summary
        </h4>
        <p className="text-sm text-muted-foreground leading-relaxed">
          {result.summary}
        </p>
      </div>

      <div className="rounded-xl border border-border p-4">
        <h4 className="text-sm font-medium mb-3 flex items-center gap-2">
          <Fingerprint className="h-4 w-4 text-primary" />
          VOICE SCAM FINGERPRINT
        </h4>
        <VoiceFingerprint signals={result.signals} />
      </div>

      {result.signals.length > 0 && (
        <div className="rounded-xl border border-border p-4 space-y-4">
          <h4 className="text-sm font-medium">Why was this flagged?</h4>
          {result.signals.map((signal) => (
            <div
              key={signal.id}
              className="border-l-2 border-primary/30 pl-3 space-y-1.5"
            >
              <div className="flex items-center gap-2 flex-wrap">
                <p className="text-sm font-semibold">{signal.label}</p>
                <span className="text-xs text-muted-foreground tabular-nums">
                  confidence {signal.confidence}%
                </span>
              </div>
              <p className="text-xs text-muted-foreground">
                Pattern: {signal.evidence.map((e) => `“${e}”`).join(", ")}
              </p>
              <p className="text-sm text-muted-foreground">{signal.explanation}</p>
              <p className="text-sm">
                <span className="font-medium">Recommended action: </span>
                {signal.recommendation}
              </p>
            </div>
          ))}
        </div>
      )}

      {isHighRisk && (
        <div className="rounded-xl border border-destructive/40 bg-destructive/5 p-5">
          <h4 className="font-semibold text-destructive flex items-center gap-2 mb-3">
            <Siren className="h-5 w-5" />
            WHAT SHOULD YOU DO NOW?
          </h4>
          <ol className="space-y-2.5">
            {result.protectionSteps.map((step, i) => (
              <li key={i} className="flex gap-3 text-sm">
                <span className="h-5 w-5 rounded-full bg-destructive text-white text-xs flex items-center justify-center shrink-0 mt-0.5">
                  {i + 1}
                </span>
                <span className="leading-relaxed">{step}</span>
              </li>
            ))}
          </ol>
          <div className="mt-4 flex flex-wrap gap-3">
            <Link
              href="https://cybercrime.gov.in"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-sm font-medium text-primary hover:underline"
            >
              Report at cybercrime.gov.in
            </Link>
            <Link
              href="https://www.cybercrime.gov.in"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-sm font-medium text-primary hover:underline"
            >
              National Cyber Crime Reporting Portal
            </Link>
          </div>
        </div>
      )}

      <div className="rounded-xl border border-border p-4 space-y-4">
        <h4 className="text-sm font-medium">Transcript</h4>
        <TranscriptDisplay transcript={result.transcript} signals={result.signals} />
      </div>

      <div className="rounded-xl border border-border p-4 space-y-3">
        <EvidenceExport audio={audio} result={result} />
      </div>

      <div className="rounded-xl border border-border/60 bg-muted/20 p-3.5">
        <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground">
          <span>Duration: {formatDuration(result.metadata.durationSeconds)}</span>
          <span>Type: {result.metadata.fileType}</span>
          <span>Size: {formatFileSize(result.metadata.fileSizeBytes)}</span>
          <span>Status: {result.metadata.processingStatus}</span>
        </div>
      </div>

      <div className="flex flex-wrap justify-between items-center gap-3 border-t pt-4">
        {onReset && (
          <Button type="button" variant="outline" onClick={onReset}>
            <RotateCcw className="h-4 w-4 mr-2" />
            Check Something Else
          </Button>
        )}
        <Link
          href="/report"
          className="inline-flex items-center gap-1.5 text-sm font-medium text-primary hover:underline"
        >
          <LifeBuoy className="h-4 w-4" />
          Report an incident & get recovery help
        </Link>
      </div>
    </div>
  );
}